include:
  - infrastructure/docker-compose.yml

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - /usr/src/app/node_modules
    env_file: "frontend/.env"
    environment:
      - NODE_ENV=development

    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
#      target: dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - /app/__pycache__
    env_file: "backend/.env"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf  # This one took me the ages to figure out. Gotta make sure we're not using protobuf at this point.
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318
