include:
  - telemetry-compose.yml
  - feature-flags-compose.yml

volumes:
  pgdata:

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: open_experiment
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d open_experiment -U postgres']
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 20s

  db_admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


